# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dee0feac17d41cc431fcbb59a2f6c9a09c0da7364baab65ae8fcf5211b8cff9a64d31d00a2e4000755ca91d7ab3dca0cebd8f9dd3894570daed836c4f41ccf21

test:
  secret_key_base: 2bfab19ad1db7bfe3d2c297d165eab9146ab3efe3eada44c8d4aeb07373b14199b2b41e3b0ef3755a46c7c66718eb472cdafb2f12f63c8d016d433e6ecb389c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
